CREATE TABLE users (
 id INT(11) NOT NULL AUTO_INCREMENT,
 first_name VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
 last_name VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
 email VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
 password VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
 created DATETIME NOT NULL,
 modified DATETIME NOT NULL,
 PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE login (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    PRIMARY KEY (id)
);